### ISSUE TITLE
Persist switching a job from a list to another

### ISSUE THREAD

**Issue by renniehaylock** [SpencerLee/Huntr#2]

**Comment by SamirMarin** [comment]
I can do this one. I was looking at it today.. Just realize that since each Job is dependent on it's list you have to update the job also not just simply give the job to the list.. But I think I know how to do it now. I'm heading to bed now. But I try and get it done by tmr night. It's looking good by the way! Good work!

**Comment by SamirMarin** [comment]
so right now persisting is working when moving from one list to another.. 

TODO: is saving the order within the list when the user mover jobs within the same list.. also right now the persisting when refreshed sometimes reorders the jobs.. this fix will come along with the fix for allowing order persistence within same list.

**Comment by SamirMarin** [comment]
Complete-- I believe the persisting is working fully-- persist when organizing jobs within list.. and also persist in correct order when modifying jobs from list to list.
