### ISSUE TITLE
CORS is messing up with the company logo displaying... we need to serve these from our own CDN

### ISSUE THREAD

**Issue by renniehaylock** [SpencerLee/Huntr#5]

**Comment by SamirMarin** [comment]
So i've looked into the CND thing.. Man glass door should really put some headers in their images for CORS use lol! (but myb the don't want to). In either case the easier to implement since it basically come pre-set for image managing i think is http://cloudinary.com/ however the free use is not great especially if we use during development.. I think it gives us only 7000 free image manipulations per month which is not great. We can go about it with other CND.. amazon Cloud front is an option I don't think it be quite as easy to implement but we do get something like 50 GB Data Transfer Out and 2,000,000 HTTP and HTTPS Requests each month for one year as part of the new sign up deal or something.. Which is probably plenty for now.... For the time being I found work around using the clear bit free logo api.. We can use glass doors to get the domains for companies and make a call to the clear bit free logo api with the domain.. The clear bit logo api is pretty good has all main companies it even finds the rungo logo--> it does miss some but so does glass door. Im not sure which one has more logos? In either case it seems to be working pretty good so it can be a good temp solution while we figure out what to do with the logos.. I think we should start storing the logos. I think we can download the image in bits or something.. And then maybe get a CND going and only use it if its a logo we don't have..

here is a link https://clearbit.com/logo -- i feel like this api is better for logos than even the glass door when playing around with it on this link.. It's just that is limited to having to enter the domain of the company.. clearbit does offer other APIs that would be cool to use for company search but they are not cheap to use.
