### ISSUE TITLE
Get Gmail messages server side

### ISSUE THREAD

**Issue by renniehaylock** [SpencerLee/Huntr#6]
Expose an endpoint on our routes to get messages given a query... We use the user's auth and refresh tokens, which we are getting from passport js... this way we don't need to deal with authing users in the client side too... https://github.com/google/google-api-nodejs-client

**Comment by SamirMarin** [comment]
added a route to authenticate user on server side... currently we obtain a new access token each time we need one..

Todo: when we obtain access token we also obtain an expire time for that access token.. We need add routes to save the new access token obtained and the expiry time of that access token.. We then need to add a check so that we only obtains  a new access token when the current access token has expired. The access token is obtained using the the refresh token.

Todo: we need figure out a way to obtain expiry time for access token when we first log in.. Currently we only have functionality that obtain access token expiry time when we obtain access token after already being logged in.

Todo: with the current change in authenticating user.. by being able to get new access token with refresh token.. we lost the ability to count the number messages since this part renders prior to the messages being obtained since we are making call to the google api and to the data base in order to obtain this new access token.. We need to update this message count so that it may render after.. For now I took away the message count view from the UI and it just says messages.

Todo: next time you pull be sure to run npm install since I am using the google-refresh-token module.

--I will try to complete this few additional task in the next few days..
